#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x58D0EE648A48B3BB (faure@kde.org)
#
Name     : kservice
Version  : 5.59.0
Release  : 18
URL      : https://download.kde.org/stable/frameworks/5.59/kservice-5.59.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.59/kservice-5.59.0.tar.xz
Source99 : https://download.kde.org/stable/frameworks/5.59/kservice-5.59.0.tar.xz.sig
Summary  : Advanced plugin and service introspection
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.1
Requires: kservice-bin = %{version}-%{release}
Requires: kservice-data = %{version}-%{release}
Requires: kservice-lib = %{version}-%{release}
Requires: kservice-license = %{version}-%{release}
Requires: kservice-locales = %{version}-%{release}
Requires: kservice-man = %{version}-%{release}
BuildRequires : bison-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : docbook-xml
BuildRequires : flex
BuildRequires : kconfig
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kcrash-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kdoctools-dev
BuildRequires : ki18n-dev
BuildRequires : libxml2
BuildRequires : libxslt
BuildRequires : qtbase-dev mesa-dev

%description
# KService
Plugin framework for desktop services
## Introduction
KService provides a plugin framework for handling desktop services. Services can
be applications or libraries. They can be bound to MIME types or handled by
application specific code.

%package bin
Summary: bin components for the kservice package.
Group: Binaries
Requires: kservice-data = %{version}-%{release}
Requires: kservice-license = %{version}-%{release}

%description bin
bin components for the kservice package.


%package data
Summary: data components for the kservice package.
Group: Data

%description data
data components for the kservice package.


%package dev
Summary: dev components for the kservice package.
Group: Development
Requires: kservice-lib = %{version}-%{release}
Requires: kservice-bin = %{version}-%{release}
Requires: kservice-data = %{version}-%{release}
Provides: kservice-devel = %{version}-%{release}
Requires: kservice = %{version}-%{release}
Requires: kservice = %{version}-%{release}

%description dev
dev components for the kservice package.


%package lib
Summary: lib components for the kservice package.
Group: Libraries
Requires: kservice-data = %{version}-%{release}
Requires: kservice-license = %{version}-%{release}

%description lib
lib components for the kservice package.


%package license
Summary: license components for the kservice package.
Group: Default

%description license
license components for the kservice package.


%package locales
Summary: locales components for the kservice package.
Group: Default

%description locales
locales components for the kservice package.


%package man
Summary: man components for the kservice package.
Group: Default

%description man
man components for the kservice package.


%prep
%setup -q -n kservice-5.59.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560027411
mkdir -p clr-build
pushd clr-build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1560027411
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kservice
cp COPYING %{buildroot}/usr/share/package-licenses/kservice/COPYING
cp COPYING.GPL3 %{buildroot}/usr/share/package-licenses/kservice/COPYING.GPL3
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/kservice/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang kservice5
## install_append content
mv %{buildroot}/etc/xdg/* %{buildroot}/usr/share/xdg/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kbuildsycoca5

%files data
%defattr(-,root,root,-)
/usr/share/kservicetypes5/application.desktop
/usr/share/kservicetypes5/kplugininfo.desktop
/usr/share/xdg/kservice.categories
/usr/share/xdg/menus/applications.menu

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KService/KAutostart
/usr/include/KF5/KService/KDBusServiceStarter
/usr/include/KF5/KService/KMimeTypeTrader
/usr/include/KF5/KService/KPluginInfo
/usr/include/KF5/KService/KPluginTrader
/usr/include/KF5/KService/KService
/usr/include/KF5/KService/KServiceAction
/usr/include/KF5/KService/KServiceGroup
/usr/include/KF5/KService/KServiceType
/usr/include/KF5/KService/KServiceTypeProfile
/usr/include/KF5/KService/KServiceTypeTrader
/usr/include/KF5/KService/KSycoca
/usr/include/KF5/KService/KSycocaEntry
/usr/include/KF5/KService/KSycocaType
/usr/include/KF5/KService/KToolInvocation
/usr/include/KF5/KService/kautostart.h
/usr/include/KF5/KService/kdbusservicestarter.h
/usr/include/KF5/KService/kmimetypetrader.h
/usr/include/KF5/KService/kplugininfo.h
/usr/include/KF5/KService/kplugintrader.h
/usr/include/KF5/KService/kservice.h
/usr/include/KF5/KService/kservice_export.h
/usr/include/KF5/KService/kserviceaction.h
/usr/include/KF5/KService/kservicegroup.h
/usr/include/KF5/KService/kservicetype.h
/usr/include/KF5/KService/kservicetypeprofile.h
/usr/include/KF5/KService/kservicetypetrader.h
/usr/include/KF5/KService/ksycoca.h
/usr/include/KF5/KService/ksycocaentry.h
/usr/include/KF5/KService/ksycocatype.h
/usr/include/KF5/KService/ktoolinvocation.h
/usr/include/KF5/kservice_version.h
/usr/lib64/cmake/KF5Service/KF5ServiceConfig.cmake
/usr/lib64/cmake/KF5Service/KF5ServiceConfigVersion.cmake
/usr/lib64/cmake/KF5Service/KF5ServiceMacros.cmake
/usr/lib64/cmake/KF5Service/KF5ServiceTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5Service/KF5ServiceTargets.cmake
/usr/lib64/libKF5Service.so
/usr/lib64/qt5/mkspecs/modules/qt_KService.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5Service.so.5
/usr/lib64/libKF5Service.so.5.59.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kservice/COPYING
/usr/share/package-licenses/kservice/COPYING.GPL3
/usr/share/package-licenses/kservice/COPYING.LIB

%files man
%defattr(0644,root,root,0755)
/usr/share/man/ca/man8/desktoptojson.8
/usr/share/man/ca/man8/kbuildsycoca5.8
/usr/share/man/de/man8/desktoptojson.8
/usr/share/man/de/man8/kbuildsycoca5.8
/usr/share/man/es/man8/desktoptojson.8
/usr/share/man/es/man8/kbuildsycoca5.8
/usr/share/man/it/man8/desktoptojson.8
/usr/share/man/it/man8/kbuildsycoca5.8
/usr/share/man/man8/desktoptojson.8
/usr/share/man/man8/kbuildsycoca5.8
/usr/share/man/nl/man8/desktoptojson.8
/usr/share/man/nl/man8/kbuildsycoca5.8
/usr/share/man/pt/man8/desktoptojson.8
/usr/share/man/pt/man8/kbuildsycoca5.8
/usr/share/man/pt_BR/man8/desktoptojson.8
/usr/share/man/pt_BR/man8/kbuildsycoca5.8
/usr/share/man/sv/man8/desktoptojson.8
/usr/share/man/sv/man8/kbuildsycoca5.8
/usr/share/man/uk/man8/desktoptojson.8
/usr/share/man/uk/man8/kbuildsycoca5.8

%files locales -f kservice5.lang
%defattr(-,root,root,-)

